### Get all inventory
GET http://127.0.0.1:5000/inventory

### Get one inventory item
GET http://127.0.0.1:5000/inventory/1

### Add a new inventory item
POST http://127.0.0.1:5000/inventory
Content-Type: application/json

{
    "name": "Orange Juice",
    "brand": "Minute Maid",
    "price": 250,
    "stock": 18
}

### Update an inventory item
PATCH http://127.0.0.1:5000/inventory/1
Content-Type: application/json

{
    "price": 400,
    "stock": 25
}

### Delete an inventory item
DELETE http://127.0.0.1:5000/inventory/2

### Search Product
GET http://127.0.0.1:5000/search/737628064502